name: Solar System Workflow 

on:
    workflow_dispatch:
    push:
        branches:
           - main
           - 'feature/*'


jobs:
    unit-testing:
        name: Unit Test
        strategy:
          matrix:
              nodejs_version: [18, 19, 20]
              operating_system: [ubuntu-latest, macos-latest]
              exclude:
                  - nodejs_version: 18
                    operating_system: [macos-latest]
        runs-on: ${{ matrix.nodejs_version}}
        steps:
        - name: checkout Repositiory
          uses: actions/checkout@v4
        
        - name: Setup Nodejs Version - ${{ matrix.nodejs_version}}
          uses: actions/setup-node@v3
          with: 
            node-version: ${{ matrix.operating_system}}

        - name: Cache NPM Dependencies
          uses: actions/cache@v3
          with:
            path: node-modules
            key: ${{ runner.os}}-node-modules-${{ hashFiles('package-lock,json') }}
        
        - name: Install Dependecies
          run: npm install

        - name: Unit Test
          id: nodejs-unit-testing-step
          run: npm test 

        - name: Archive Test Result
          if: steps.nodejs-unit-testing-step == 'failure' || steps.nodejs-unit-testing-step == 'success'
          uses: actions/upload-artifact@v3
          with:
            name: Mocha Test-Result
            path: test-result.xml
    code-coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup NodeJS version - 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install
      
      - name: Check Code Coverage
        continue-on-error: true
        run: npm run coverage
      
      - name: Archive Test Result
        uses: actions/upload-artifact@v3
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5