name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
           - main
           - 'feature/*'
jobs:
    unit-testing:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repositiory
          uses: actions/checkout@v4
        
        - name: Setup Nodejs Version - 18
          uses: actions/setup-node@v3
          with: 
            node-version: 18
        
        - name: Install Dependecies
          run: npm install